// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYonzVPw4dLxo3QFm9V4Vi1LBZezaHcB4',
    appId: '1:360304385913:web:e67f4405ad7801d4a819a8',
    messagingSenderId: '360304385913',
    projectId: 'elred-d7889',
    authDomain: 'elred-d7889.firebaseapp.com',
    storageBucket: 'elred-d7889.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA12YSqax3u9Q82S36pbjzgwYWCFMy99Jk',
    appId: '1:360304385913:android:7ded0aea6ea979eea819a8',
    messagingSenderId: '360304385913',
    projectId: 'elred-d7889',
    storageBucket: 'elred-d7889.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4V5Y3xYFFD457jmQmqVNQrU9-XkHJJyU',
    appId: '1:360304385913:ios:81a10077b412ea7ca819a8',
    messagingSenderId: '360304385913',
    projectId: 'elred-d7889',
    storageBucket: 'elred-d7889.appspot.com',
    iosClientId: '360304385913-fg368kkjnformvo6djbfit2ke0mpr6d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.elredTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4V5Y3xYFFD457jmQmqVNQrU9-XkHJJyU',
    appId: '1:360304385913:ios:81a10077b412ea7ca819a8',
    messagingSenderId: '360304385913',
    projectId: 'elred-d7889',
    storageBucket: 'elred-d7889.appspot.com',
    iosClientId: '360304385913-fg368kkjnformvo6djbfit2ke0mpr6d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.elredTest',
  );
}
